// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWQW/bOgz+K4LeO7qx+9JD4dtDM2zBVnTohmFA0YNiM7E6W1IpukMa5L8PlOMkbtwm",
	"3Qb0kkvriOT3UST1SQuZ2cpZA4a8TBeyAJUDhs/vJ9eK4OSTrjQ1f3k1B5+hdqStkan8WoAwdTUBFHYq",
	"VFnan5ALhPsaPHmhjaACRFYjgiHhALXNZSR9VkClGI7mDmQqtSGYAcrlMuryXkOltNFmto8bW8e/y+5h",
	"7649ZNbkXpQwpd/mhPvaA52MR/1sqz0JnYvaQy7ICkKV/Qhk1gGq4NzD4wm5ekvmaYyhuRdl7QmQPx0y",
	"AGkIBp33JRlJoyrog43aFTu5g4zY9R2ixUubQ7kLn8Okno0bDk0lB454SYxHMnoKHklgqAubw3ZAwBdh",
	"9bmQEZDSpd+Nag09aRdE7gspqv1Twg9ryxPWrfpU4L2adcIuV0tRT9G4oRohl+lNN+PtPW9Qo3XhdvK8",
	"jbpbbAq/sz8m1WZq++ZLe6F9GKUtC4/2akq+6Ufx/+fxQG6ouhYxHCQykg+AvsE8HSSDhMtiHRjltEzl",
	"cJAMhjKSTlERGhNnDUb4MWvO2XqUeUTke6CL1odL5p01vpmj/5KE/2XWEJgQqpwrdRaC4zvPWSy2ToMm",
	"qELgvwhTmcp/4o3uxatzEbeHYjPUClHNm+J1i3b1kb3OXpmFKsurqUxvXk5jq43L2x7uiVpLLI/DPsXu",
	"o1oFxT0RLyrwwVibqGc19RVYHNGjk3sQNr6hiGfJ6Rs0qzaqpgIMMRHkHbE+tu7g1g3frHUW9WOnb+Em",
	"ratK4bzRKH73iLWYsXktbfFC58tD9C0ou1OoKmgk8WYhNSfBcinb65dv5+27g7CGF98Wt38omwep5VEd",
	"j+p4VMejOj6njq02islctDl7wIdW52osZRqetWkclzZTZWE9pefJeRIrp+OHU87gVwAAAP//p/angqoO",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
